In [1]:
import torch
from torchvision.ops.boxes import box_iou
from torchmetrics.detection import MeanAveragePrecision

C:\ProgramData\Anaconda3\envs\Newenv_3_10\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
MAP = MeanAveragePrecision(iou_thresholds=[0.1])

In [37]:
q = torch.randn((1, 4,8, int(512/8)))
k= torch.randn((1, 144,8, 64))

In [33]:
torch.tensordot(q,k,dims=([1],[0]))

64.0

In [18]:
a=torch.randn((1, 1, 6))
a

tensor([[[-0.2830,  1.5214,  0.3321,  1.0547, -0.5133,  1.1126]]])

In [38]:
a.reshape(1,1,2,3).reshape(1,1,3,2)

tensor([[[[-0.2830,  1.5214],
          [ 0.3321,  1.0547],
          [-0.5133,  1.1126]]]])

In [29]:
a.reshape(1,1,2,3).transpose(2,3)

tensor([[[[-0.2830,  1.0547],
          [ 1.5214, -0.5133],
          [ 0.3321,  1.1126]]]])

In [31]:
a.reshape(1,1,2,3).permute(0,2,1,3).permute(0,2,1,3)

tensor([[[[-0.2830,  1.5214,  0.3321],
          [ 1.0547, -0.5133,  1.1126]]]])

In [16]:
torch.matmul(q,k.transpose(1, 2)).shape

torch.Size([100, 4, 3])

In [9]:
k

tensor([[[-0.3620, -1.0061],
         [-0.8922, -0.6622],
         [-2.3080,  2.5782]]])

In [10]:
k.transpose(1, 2)

tensor([[[-0.3620, -0.8922, -2.3080],
         [-1.0061, -0.6622,  2.5782]]])